### ISSUE TITLE
lowercase attributes

### ISSUE THREAD

**Issue by sotten** [Laravel-Lang/attributes#44]
- Laravel-Lang Attributes Version: 2.0.4
- PHP Version: 8.1.3

### Description:
Was it intended to write all attributes in lower case or is this a script error?

**Comment by andrey-helldar** [comment]
No, not a mistake. The fact is that in the English version, the validator sentences begin with the word "The". Thus, if we capitalize attribute names, we get something like `The Name must be accepted.` instead of `The name must be accepted.`.

But if we write with a small letter, then the sentence will look correct.

At the same time, Laravel has a word conversion mechanism:

```
__('The :attribute must be accepted.', ['attribute' => 'name']) // The name
__('The :Attribute must be accepted.', ['attribute' => 'name']) // The Name
__('The :ATTRIBUTE must be accepted.', ['attribute' => 'name']) // The NAME

__('The :attribute must be accepted.', ['attribute' => 'NAME']) // The NAME
__('The :Attribute must be accepted.', ['attribute' => 'NAME']) // The NAME
__('The :ATTRIBUTE must be accepted.', ['attribute' => 'NAME']) // The NAME
```

**Comment by andrey-helldar** [comment]
At the same time, the script does not change the words written by the developer, since, for example, in German, nouns can begin with a capital letter.

**Comment by andrey-helldar** [comment]
At the same time, the script does not change the words written by the developer, since, for example, in German, nouns can begin with a capital letter.

If you ask why all the names in the [locales/de/php.json](https://github.com/Laravel-Lang/attributes/blob/main/locales/de/php.json) file are with a small letter, then here I made them with a small letter when I updated all the states. For this I apologize.
